"""Shared fixtures and helpers for the odk-central-k8s unit tests."""

from __future__ import annotations

import json
import pathlib
from typing import Any

import charm as charm_module
import pytest
import requests
from charm import CONFIG_PATH, NGINX_TEMPLATE_DIR, OdkCentralCharm, generate_secret
from charms.odk_central_k8s.v0.odk_enketo import SECRET_LENGTHS
from ops import testing

DB_ENDPOINTS = "postgresql-k8s-primary.odk.svc.cluster.local:5432"
NGINX_CONF = f"{NGINX_TEMPLATE_DIR}/odk.conf.template"
CLIENT_CONFIG = f"{NGINX_TEMPLATE_DIR}/client-config.json.template"


def migrations_exec(return_code: int = 0, stdout: str = "migrations complete") -> testing.Exec:
    """Return a fake exec result for the migration command."""
    return testing.Exec(
        command_prefix=["node", "./lib/bin/run-migrations"],
        return_code=return_code,
        stdout=stdout,
    )


@pytest.fixture(autouse=True)
def api_is_healthy(monkeypatch: pytest.MonkeyPatch) -> None:
    """Make the API health poll answer immediately.

    Without this every test would spend the charm's full API_READY_TIMEOUT
    waiting for a service that does not exist in a unit test.
    """

    class Healthy:
        status_code = 200

    monkeypatch.setattr(charm_module.requests, "get", lambda *a, **k: Healthy())


@pytest.fixture
def api_is_unhealthy(monkeypatch: pytest.MonkeyPatch) -> None:
    """Make the API health poll fail without waiting."""
    monkeypatch.setattr(charm_module, "API_READY_TIMEOUT", 0)
    monkeypatch.setattr(charm_module, "API_POLL_INTERVAL", 0)

    def refuse(*args: object, **kwargs: object) -> None:
        raise requests.ConnectionError("connection refused")

    monkeypatch.setattr(charm_module.requests, "get", refuse)


@pytest.fixture
def ctx() -> testing.Context[OdkCentralCharm]:
    """Return a Scenario context for the charm."""
    return testing.Context(OdkCentralCharm)


@pytest.fixture
def service() -> testing.Container:
    """Return a connectable service container whose migrations succeed."""
    return testing.Container("service", can_connect=True, execs={migrations_exec()})


@pytest.fixture
def nginx() -> testing.Container:
    """Return a connectable nginx container."""
    return testing.Container("nginx", can_connect=True)


@pytest.fixture
def postgresql() -> testing.Relation:
    """Return a complete postgresql_client relation."""
    return testing.Relation(
        "postgresql",
        remote_app_name="postgresql-k8s",
        remote_app_data={
            "endpoints": DB_ENDPOINTS,
            "username": "relation-7",
            "password": "hunter2",
            "database": "odk",
        },
    )


@pytest.fixture
def ingress() -> testing.Relation:
    """Return a settled traefik ingress relation."""
    return testing.Relation(
        "ingress",
        remote_app_name="traefik-k8s",
        remote_app_data={"ingress": json.dumps({"url": "https://odk.ingress.example/"})},
    )


@pytest.fixture
def shared_secrets() -> set[testing.Secret]:
    """Return the three shared secrets, already generated by the leader."""
    return {
        testing.Secret(
            tracked_content={"value": generate_secret(length)},
            label=label,
            owner="app",
        )
        for label, length in SECRET_LENGTHS.items()
    }


# Helpers for reading what the charm pushed into the containers.


def container_named(state: testing.State, name: str) -> testing.Container:
    """Return one container from a resulting state by name."""
    return next(c for c in state.containers if c.name == name)


def config_file(state: testing.State, ctx: testing.Context[OdkCentralCharm]) -> pathlib.Path:
    """Return the path of the config.json the charm pushed into the container."""
    root = container_named(state, "service").get_filesystem(ctx)
    return root / CONFIG_PATH.lstrip("/")


def rendered_config(state: testing.State, ctx: testing.Context[OdkCentralCharm]) -> dict[str, Any]:
    """Return the API service's rendered config.json."""
    document: dict[str, Any] = json.loads(config_file(state, ctx).read_text())
    return document["default"]


def nginx_environment(state: testing.State) -> dict[str, str]:
    """Return the environment the nginx service was configured with."""
    layer = container_named(state, "nginx").layers["nginx"]
    return dict(layer.services["nginx"].environment)


def pushed_to_nginx(state: testing.State, ctx: testing.Context[OdkCentralCharm], path: str) -> str:
    """Return the content of a file the charm pushed into the nginx container."""
    root = container_named(state, "nginx").get_filesystem(ctx)
    return (root / path.lstrip("/")).read_text()
